config/routes.rb
Rails.application.routes.draw do
  get 'persons/profile'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'persons/profile', as: 'user_root'

  resources :sketches do
    resources :comments
  end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :sketch
end

app/models/sketch.rb
class Sketch < ApplicationRecord
  has_many :comments, :dependent => :destroy
  validates :title, presence: true, length: {minimum: 5}

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sketches, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @sketch = Sketch.find(params[:sketch_id])
    @comment = @sketch.comments.create(comment_params)

    redirect_to sketch_path(@sketch)
  end

  private def comment_params
    params.require(:comment).permit(:username,:text)
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
    @user = current_user
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  def after_sign_in_path_for(resource)
    current_user_path
  end
end

app/controllers/sketches_controller.rb
class SketchesController < ApplicationController

  def index
    @sketches = Sketch.all
  end

  def show
    @sketch = Sketch.find(params[:id]);
  end

  def new

  end

  def create
    # @sketch = Sketch.new(sketch_params)

    @sketch = current_user.sketches.create(sketch_params)

    @sketch.save
      redirect_to @sketch
  end

  def edit
    @sketch = Sketch.find(params[:id])
  end

  def update
    @sketch = Sketch.find(params[:id])
    if(@sketch.update(sketch_params))
      redirect_to sketch_path
    else
      render 'edit'
    end
  end

  def destroy
    @sketch = Sketch.find(params[:id]);

    @sketch.destroy
     redirect_to sketches_path
  end


  private def sketch_params
    params.require(:sketch).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sketcherapplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
              <div class="dropdown-menu" aria-labelledby="dropdown09">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
          <form class="form-inline my-2 my-md-0">
            <% if user_signed_in? %>
          <span>Здравствуйте, <%= current_user.email %></span>
            <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
              <% else %>
          <%= link_to 'Войти', new_user_session_path %>  или  <%= link_to 'Зарегистрироваться', new_user_registration_path %>
              <% end %>
          </form>
        </div>
      </nav>
    <div class="container">
      <%= yield %>
    </div>
    </body>
</html>

app/views/persons/profile.html.erb
<h1 class="text-center">Страничка пользовтеля</h1>
<br>
<div class="row">
  <div class="col-md-4 col-lg-4">
    <img src="https://avatarfiles.alphacoders.com/983/98389.png" style="width:100%" class="rounded img-thumbnail">
  </div>
  <div class="col-md-4 col-lg-4 bg-light ">
    <h3 class="font-weight-bold">Имя пользователя:</h3>
    <h4 class="font-weight-normal"><%= @user.email %></h4>
  </div>
  <div class="col-md-4 col-lg-4 bg-light">

  </div>
</div>
<hr>

<div class="row">
  <div class="col-md-4 col-lg-4">
    <h3>Сортировка и добавление</h3>
    <%= link_to "Добаить запись", new_sketch_url , class: "btn btn-success btn" %>
    <hr>
  </div>
  <div class="col-md-8 col-lg-8">
    <h3>Все посты</h3>
    <% @user.sketches.each do |sketch| %>
      <div class="card border-dark mb-3" style="width: 100%">
        <div class="card-header"><%= sketch.title %></div>
        <div class="card-body text-dark">
          <img src="https://i2.rozetka.ua/goods/4326733/39860688_images_4326733544.jpg" class="card-img-top">
          <h5 class="card-title">Dark card title</h5>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/sketches/edit.html.erb
<h1>Редактирование<h1>
<%= form_for :sketch, url: sketches_path do |f| %>
  <h3>Имя</h3>
  <%= f.text_field :title ,class: "form-control"%>
  <h3>Содержание</h3>
  <%= f.text_area :text,class:  "form-control"%>
  <%= f.submit class: "btn btn-outline-primary btn-large" %>
<% end %>

app/views/sketches/index.html.erb
<% @sketches.each do |sketch| %>
  <h3><%= sketch.title %><h3>
<% end %>

app/views/sketches/new.html.erb
<h1>Добавление записи<h1>
<%= form_for :sketch, url: sketches_path do |f| %>
  <h3>Имя</h3>
  <%= f.text_field :title ,class: "form-control"%>
  <h3>Содержание</h3>
  <%= f.text_area :text,class:  "form-control"%>
  <%= f.submit class: "btn btn-outline-primary btn-large" %>
<% end %>

app/views/sketches/show.html.erb
<br>
<h1><%= @sketch.title %></h1>
<p><%= @sketch.text %></p>
<hr>
<%= link_to "Удалить запись" , sketch_path, method: :delete, class: "btn btn-danger" %>
<%= link_to "Редактировать запись" , edit_sketch_path, class: "btn btn-warning" %>
<hr>
<h1>Комментарии</h1>
<% @sketch.comments.each do |comment| %>
  <div class="alert alert-light"
    <p><strong><%= comment.username %>: </strong><%= comment.text %></p>
  </div>
<% end %>
<hr>
<h1>Добавление комментария<h1>
<%= form_for ([@sketch, @sketch.comments.build]) do |f| %>
  <h3>Пользователь</h3>
  <%= f.text_field :username ,class: "form-control"%>
  <h3>Комментарии</h3>
  <%= f.text_area :text,class:  "form-control"%>
  <%= f.submit("Добавить комментарий",{class: "btn btn-success btn-large"}) %>
<% end %>